### ISSUE TITLE
Issue in tests: duplicated method "defaultValue" in testComplexAnyOf

### ISSUE THREAD

**Issue by rafaelgonzalezsimon** [sngular/scs-multiapi-plugin#317]
It was detected in testComplexAnyOf .
The object definition "enumField" has "defaultValue" and "defaultValues" parameters and this creates duplicate method defaultValue, one for the defaultValues builder and the other for the defaultValue parameter.

It can be fixed by removing the parameter "defaultValue" from "enumFiled".

**Comment by jemacineiras** [comment]
Hi,
That is not an issue that `defaultValues` is a List so `Builder` we generate will contain a method for a `defaultValues(List` and a `defaultValue `to add a single element to the list. 
In that example, the file was right but the builder generate a controversial one, since is a `legal `one but not a `valid ` one.
